#!/usr/bin/env bash

function create_nginx_config() {
  local server_name="$1"
  local upstream_server
  if [[ "$3" =~ ^(yes|y)$ ]]; then 
    upstream_server="https://$2"
  else 
    upstream_server="http://$2"
  fi
  local certificate_name="$4"
  local config=$(cat << EOF
server {
  listen  80;
  listen  [::]:80;

  server_name $server_name;

  location / {
    return 301 https://$server_name\$request_uri;
  }
}

server {
  listen              443 ssl http2;
  listen              [::]:443 ssl;
  server_name         $server_name;

  ssl_certificate     /etc/letsencrypt/live/$certificate_name/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/$certificate_name/privkey.pem;

  location / {
    proxy_set_header        Host \$host;
    proxy_set_header        X-Real-IP \$remote_addr;
    proxy_set_header        X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto https;
    proxy_set_header        Upgrade \$http_upgrade;
    proxy_set_header        Connection \$http_connection;

    proxy_http_version 1.1;

    proxy_pass $upstream_server;
  }
}
EOF
)
  printf '%s\n' "$config" > "/etc/nginx/sites-available/$server_name"
}

function enable_virtual_host() {
  ln -sf "/etc/nginx/sites-available/$1" "/etc/nginx/sites-enabled/$1"
}

function main() {
  read -rp "Server Name (e.g app.local.example.com): " server_name
  read -rp "Upstream Server (e.g 127.0.0.1:5000): " upstream_server
  read -rp "Base domain for the wildcard certificate (e.g local.example.com): " base_domain

  echo "Checking if wildcard certificate exists for $base_domain"
  if [[ -d "/etc/letsencrypt/live/$base_domain" ]]; then
    echo "Found wildcard certificate. Proceeding..."
  else 
    echo "Did not find wildcard certificate for $base_domain. Please create one and try again."
    exit 1
  fi

  read -rp "Does the upstream server require HTTPS? (yes/no) " upstream_protocol

  while true; do
    read -rp "Create nginx config? (yes/no) " confirmation
    case "$confirmation" in
      yes|y|"")
        echo "Creating config at /etc/nginx/sites-available/$server_name"
        create_nginx_config "$server_name" "$upstream_server" "$upstream_protocol" "$base_domain"

        echo "Enabling Virtual Host..."
        enable_virtual_host "$server_name"

        echo "Restarting nginx..."
        if systemctl restart nginx; then
          echo "nginx restarted successfully."
          exit 0
        else
          echo "Failed to restart nginx. Please check the configuration."
          exit 1
        fi
        ;;
      no|n)
        echo "Exiting..."
        exit 0
        ;;
      *)
        echo "Invalid input. Please answer yes or no."
        ;;
    esac
  done
}

main
